service: backend-java-api-reminder
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  profile: serverless-sunshine
  region: eu-west-2
  apiGateway:
    shouldStartNameWithService: true
  httpApi:
    cors: true
  environment:
    DB_HOST: ${file(./config.dev.json):DB_HOST}
    DB_NAME: ${file(./config.dev.json):DB_NAME}
    DB_USER: ${file(./config.dev.json):DB_USER}
    DB_PASSWORD: ${file(./config.dev.json):DB_PASSWORD}

package:
  artifact: target/reminders-java-api-dev.jar

functions:
  get-reminder-java-api:
    handler: com.sunshine.GetReminderHandler
    events:
      - httpApi:
          path: /users/{userId}/reminders/{reminderId}
          method: get
  save-reminder-java-api:
    handler: com.sunshine.SaveReminderHandler
    events:
      - httpApi:
          path: /users/{userId}/reminders
          method: post


